openapi: 3.0.3
info:
  title: Human resource information service API
  version: 1.0.0
  description: |-
    The service that stores employee information, performance reviews, and organization structure.

servers:
  - url: http://localhost:8080/api/v1/hris
    description: Local environment

tags:
  - name: employees
    description: Endpoints responsible for the employees management and viewing
  - name: organization
    description: Endpoints responsible for the viewing of the organization structure
  - name: performance-reviews
    description: Endpoints responsible for the performance review management and viewing

paths:
  /employees:
    post:
      tags:
        - employees
      description: Create a new employee
      operationId: createEmployee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEmployeeRequest'
      responses:
        '201':
          description: Employee created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateEmployeeResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /employees/{employeeId}:
    patch:
      tags:
        - employees
      description: Update employee information by id. Name, surname and email cannot be updated
      operationId: patchEmployee
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/EmployeeId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchEmployeeRequest'
      responses:
        '200':
          description: Employee updated
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - employees
      description: Get employee details by id.
      operationId: getEmployee
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/EmployeeId"
      responses:
        '200':
          description: Employee details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEmployeeResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - employees
      description: Delete the employee by id
      operationId: deleteEmployee
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/EmployeeId"
      responses:
        '200':
          description: Employee deleted
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /organization/org-chart/all:
    get:
      tags:
        - organization
      description: Get the whole organization view
      operationId: getAllOrganization
      responses:
        '200':
          description: Organization org chart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /organization/org-chart:
    get:
      tags:
        - organization
      description: Get organization sub view for the given employee
      operationId: getOrganizationSubView
      parameters:
        - name: employeeId
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/EmployeeId"
        - name: expand
          in: query
          required: false
          description: Expand the current hierarchy to the top/bottom
          schema:
            type: string
            enum: [ Top, Bottom, None ]
            default: None
        - name: step
          in: query
          required: false
          description: Expand the current hierarchy on the number of layers
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Organization org chart sub view
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /performance-reviews:
    put:
      tags:
        - performance-reviews
      description: Create or update performance review for the reviewed employee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitPerformanceReviewRequest'
      responses:
        '200':
          description: Performance review was submitted
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /performance-reviews/{employeeId}:
    get:
      tags:
        - performance-reviews
      description: Get the performance review history for the employee
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/EmployeeId"
        - name: limit
          in: query
          required: false
          description: Number of performance reviews to return within one request
          schema:
            type: integer
            maximum: 100
            minimum: 0
            default: 20
        - name: offset
          in: query
          required: false
          description: Position of performance review to start selection with
          schema:
            type: integer
            format: int64
            minimum: 0
            default: 0
      responses:
        '200':
          description: Performance review was submitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerformanceReviewHistoryResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:

    CreateEmployeeRequest:
      type: object
      required:
        - name
        - surname
        - email
        - position
      properties:
        name:
          $ref: "#/components/schemas/Name"
        surname:
          $ref: "#/components/schemas/Surname"
        email:
          $ref: "#/components/schemas/Email"
        position:
          $ref: "#/components/schemas/Position"
        supervisor:
          $ref: "#/components/schemas/EmployeeId"
        subordinates:
          type: array
          items:
            $ref: "#/components/schemas/EmployeeId"

    CreateEmployeeResponse:
      type: object
      required:
        - employeeId
      properties:
        employeeId:
          $ref: "#/components/schemas/EmployeeId"

    PatchEmployeeRequest:
      type: object
      properties:
        position:
          $ref: "#/components/schemas/Position"
        supervisor:
          $ref: "#/components/schemas/EmployeeId"
        subordinates:
          type: array
          items:
            $ref: "#/components/schemas/EmployeeId"

    GetEmployeeResponse:
      type: object
      required:
        - employeeId
        - name
        - surname
        - email
        - position
      properties:
        employeeId:
          $ref: "#/components/schemas/EmployeeId"
        name:
          $ref: "#/components/schemas/Name"
        surname:
          $ref: "#/components/schemas/Surname"
        email:
          $ref: "#/components/schemas/Email"
        position:
          $ref: "#/components/schemas/Position"
        supervisor:
          $ref: "#/components/schemas/EmployeeId"
        subordinates:
          type: array
          items:
            $ref: "#/components/schemas/EmployeeId"

    OrganizationResponse:
      type: object
      additionalProperties:
        description: Employee detail
        $ref: '#/components/schemas/Employee'

    Employee:
      type: object
      required:
        - employeeId
        - name
        - surname
        - position
      properties:
        employeeId:
          $ref: "#/components/schemas/EmployeeId"
        name:
          $ref: "#/components/schemas/Name"
        surname:
          $ref: "#/components/schemas/Surname"
        position:
          $ref: "#/components/schemas/Position"
        subordinates:
          type: array
          items:
            $ref: '#/components/schemas/Employee'

    SubmitPerformanceReviewRequest:
      type: object
      required:
        - revieweeId
        - reviewerId
        - performance
        - softSkills
        - independence
        - aspirationForGrowth
      properties:
        revieweeId:
          $ref: '#/components/schemas/EmployeeId'
        reviewerId:
          $ref: '#/components/schemas/EmployeeId'
        performance:
          $ref: '#/components/schemas/ReviewScore'
        softSkills:
          $ref: '#/components/schemas/ReviewScore'
        independence:
          $ref: '#/components/schemas/ReviewScore'
        aspirationForGrowth:
          $ref: '#/components/schemas/ReviewScore'
        comment:
          $ref: '#/components/schemas/ReviewComment'
        date:
          type: string
          format: date

    PerformanceReviewHistoryResponse:
      type: object
      required:
        - reviews
        - limit
        - offset
      properties:
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/EmployeePerformanceReview'
        limit:
          type: integer
        offset:
          type: integer
          format: int64

    EmployeePerformanceReview:
      type: object
      required:
        - revieweeId
        - performance
        - softSkills
        - independence
        - aspirationForGrowth
        - createdAt
      properties:
        revieweeId:
          $ref: '#/components/schemas/EmployeeId'
        performance:
          $ref: '#/components/schemas/ReviewScore'
        softSkills:
          $ref: '#/components/schemas/ReviewScore'
        independence:
          $ref: '#/components/schemas/ReviewScore'
        aspirationForGrowth:
          $ref: '#/components/schemas/ReviewScore'
        comment:
          $ref: '#/components/schemas/ReviewComment'
        createdAt:
          type: string
          format: date

    ReviewScore:
      type: integer
      minimum: 1
      maximum: 10

    ReviewComment:
      type: string
      maximum: 2000

    EmployeeId:
      description: Employee id in uuid format
      type: string
      format: uuid
      example: 00000000-0000-0000-0000-000000000002

    Name:
      type: string
      minimum: 1
      maximum: 50
      example: Frodo

    Surname:
      type: string
      minimum: 1
      maximum: 50
      example: Baggins

    Email:
      type: string
      format: email
      minimum: 15
      maximum: 60
      example: frodo.baggins@mycompany.org

    Position:
      description: Employee position in the organization
      type: string
      enum: [ CEO, CTO, CPO, SoftwareEngineer, EngineeringManager, ProductManager ]
      example: SoftwareEngineer

    ErrorResponse:
      type: object
      required:
        - errorMessage
      properties:
        errorMessage:
          type: string
          example: Internal error
